v1.0.35 github actions

diff --git a/scripts/push-action b/scripts/push-action
--- a/scripts/push-action
+++ b/scripts/push-action
@@ -18,14 +18,29 @@ fi
 
 export BABEL_ENV=deploy
 nuxt --version
+
 echo "$SCRIPT: wiki-images"
-$DIR/wiki-images
-$DIR/nuxt-routes.js
+$DIR/wiki-images; RC=$? || exit $RC
+
+echo "$SCRIPT: nuxt-routes"
+$DIR/nuxt-routes.js; RC=$? || exit $RC
+
+echo "$SCRIPT: nuxt generate"
 export CI=
 echo CI=$CI
-nuxt generate
-$DIR/git-commit-version PUSH
-npm run deploy:branch 
-RC=$?
+nuxt generate; RC=$? || exit $RC
+
+echo "$SCRIPT: git-commit-version"
+$DIR/git-commit-version PUSH; RC=$? 
+if [ "$RC" == "411" ]; then
+  echo "$SCRIPT: no changes (ok)"
+elif [ "$RC" == "0" ]; then
+  echo "$SCRIPT: changes committed (ok)"
+else
+  echo "$SCRIPT: ERROR $RC"
+fi
+
+npm run deploy:branch ; RC=$? || exit $RC
 
 echo "$SCRIPT: done => $RC"
+exit $RC
